import { Box, Divider, Typography } from '@mui/material'
import Head from 'next/head'

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Andino Chaski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="main">
        <Typography variant="h2">Dashboard</Typography>
        <Divider />
      </Box>
    </>
  )
}
