import { Box, Typography, Toolbar } from "@mui/material";

import Head from "next/head";
import Image from "next/image";

export default function Images() {
  return (
    <>
      <Head>
        <title>Andino Chaski</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        component='main'
        sx={{
          width: "660px",
          minHeight: "800px",
          px: 10,
          pt: 3,
          backgroundColor: "#8c44ee",
          margin: "0 auto",
        }}
      >
        <Toolbar sx={{ display: "flex", justifyContent: "end", mb: -4 }}>
          <Typography
            sx={{
              pr: 2,
              textTransform: "uppercase",
              letterSpacing: 0.8,
              fontSize: 12,
              fontFamily: "TT Norms Thin",
              color: "#ffffff",
            }}
          >
            Powered by
          </Typography>
          <Image
            width={120}
            height={35}
            src='/../public/img/logoAndino.png'
            alt='Logo Polygon'
          />
        </Toolbar>
        <Box>
          <Box>
            <Image
              width={180}
              height={180}
              src='/../public/img/polygon/logo polygon white.webp'
              alt='Logo Polygon'
            />
            <Typography
              variant='h6'
              sx={{
                mt: -5,
                mb: 1,
                fontWeight: "bold",
                fontFamily: "TT Norms Bold",
                color: "#ffffff",
              }}
            >
              #BuiltWithPolygon
            </Typography>
            <Typography
              variant='h2'
              sx={{
                color: "#2e2e2e",
                fontWeight: "bold",
                fontFamily: "TT Norms Bold",
              }}
            >
              Polygon Guild{" "}
              <Typography
                variant='h2'
                component='span'
                sx={{
                  color: "#ffffff",
                  display: "block",
                  fontWeight: "bold",
                  fontFamily: "TT Norms Bold",
                }}
              >
                /Lima
              </Typography>
            </Typography>
          </Box>
          <Box display='flex' sx={{ pt: 3 }}>
            <Typography
              sx={{
                fontSize: 60,
                display: "flex",
                alignItems: "center",
                pr: 8,
                fontFamily: "TT Norms Regular",
                color: "#ffffff",
              }}
            >
              28{" "}
              <Typography
                component='span'
                display='flex'
                flexDirection='column'
                sx={{ fontSize: 16, pl: 1, fontFamily: "TT Norms Regular" }}
              >
                Enero{" "}
                <Typography
                  component='span'
                  sx={{ fontSize: 16, fontFamily: "TT Norms Regular" }}
                >
                  10:00am
                </Typography>
              </Typography>
            </Typography>
            <Typography
              sx={{
                mt: 2,
                width: "200px",
                fontFamily: "TT Norms Regular",
                color: "#ffffff",
              }}
            >
              Universidad Continental, Jr.Junin 355, Miraflores
            </Typography>
          </Box>
        </Box>
      </Box>
    </>
  );
}
