import Head from "next/head";

import Header from "../components/Header";

import { useState } from "react";
import { RespondeData, SocialMediaPostResponse } from "./api/generate";

import { Toolbar, Button } from "@mui/material";

import { useForm } from "../hooks/useForm";

export default function Home() {
  const [isLoading, setisLoading] = useState(false);

  const [result, setResult] = useState<SocialMediaPostResponse[] | null>([]);

  async function onSubmit(event: Event) {
    event.preventDefault();

    setisLoading(true);

    const response = await fetch("/api/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title,
        date,
        description,
        speaker,
        link,
      }),
    });
    const responseData: RespondeData = await response.json();

    setResult(responseData?.data);
    setisLoading(false);
  }

  const { inputState, onChangeForm, onResetForm } = useForm({
    title: "CryptoMonday 14: Como crear aplicaciones web 3 en tu empresa",
    description:
      "En este segmento aremos entender a pymes y empresas pequeñas como usar esta nueva dimensión para incrementar sus ventas",
    speaker: "Paul Garcia- Tech Lead Upstream",
    date: "January 14, 2023",
    link: "https://andino.upstreamapp.com",
  });

  const { title, description, speaker, date, link } = inputState;

  console.log(result);

  return (
    <div className="scrollbar-contentAll">
      <Head>
        <title>Andino Chaski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Toolbar />

      <main className={""}>
        <Button>Go to social generator</Button>
      </main>
    </div>
  );
}
