import Head from 'next/head'
import { GetServerSideProps } from 'next'

import Header from '../components/Header'
import { Toolbar, Button } from '@mui/material'
import { mainSpeakerFunction } from '../services/speakers'

export default function Home() {
  return (
    <div className="scrollbar-contentAll">
      <Head>
        <title>Andino Chaski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Toolbar />

      <main className={''}>
        <Button>Go to social generator</Button>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async ctx => {
  await mainSpeakerFunction()

  return {
    props: {}
  }
}
