import Head from 'next/head'

import Header from '../../components/Header'
import { Toolbar, Grid, Box, Typography } from '@mui/material'
import { useForm } from '../../hooks/useForm'
import { DataSocialMedia } from '../../components/DataSocialMedia'
import { FormGenerateSocialMedia } from '../../components/FormGenerateSocialMedia'
import { useGenerateSocialEventContentMutation } from '../../graphql/generated/generated'
import { useCallback } from 'react'

function TabPanel(props: any) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role='tabpanel'
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          <Typography>{children}</Typography>
        </Box>
      )}
    </div>
  );
}

export default function Home() {
  const [doMutation, { loading: isLoading, data: result }] =
    useGenerateSocialEventContentMutation()

  const { inputState, onChangeForm, onResetForm } = useForm({
    title: 'CryptoMonday 14: Como crear aplicaciones web 3 en tu empresa',
    description:
      'En este segmento aremos entender a pymes y empresas pequeñas como usar esta nueva dimensión para incrementar sus ventas',
    speaker: 'Paul Garcia- Tech Lead Upstream',
    date: 'January 14, 2023',
    link: 'https://andino.upstreamapp.com'
  })
  const { title, description, speaker, date, link } = inputState

  const onSubmit = useCallback(async () => {
    await doMutation({
      variables: {
        body: {
          title,
          date,
          details: description,
          speaker,
          link
        }
      }
    })
  }, [date, description, doMutation, link, speaker, title])

  return (
    <div className='scrollbar-contentAll'>
      <Head>
        <title>Andino Chaski</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Toolbar />

      <main className={''}>
        <Grid
          container
          alignItems='center'
          sx={{
            minHeight: { xs: 'calc(100vh + 160px)', sm: 'calc(100vh - 64px)' }
          }}
        >
          <DataSocialMedia
            isLoading={isLoading}
            result={result?.generateSocialEventContent || []}
          />

          <FormGenerateSocialMedia
            onSubmit={onSubmit}
            onChangeForm={onChangeForm}
            onResetForm={onResetForm}
            isLoading={isLoading}
            {...inputState}
          />
        </Grid>
      </main>
    </div>
  )
}
