import Head from 'next/head'

import { Button } from '@mui/material'

export default function Home() {
  return (
    <div className="scrollbar-contentAll">
      <Head>
        <title>Andino Chaski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={''}>
        <Button>finished generating the speaker file</Button>
      </main>
    </div>
  )
}
